/**
 * Tilawa — `public/_headers` generator.
 * -----------------------------------------------------------------------------
 * Writes the header rules that Cloudflare Pages and Netlify read from a
 * `_headers` file at the site root.
 *
 * This exists because the application is a static export: there is no server to
 * run `next.config.ts`'s `headers()`, so in production the Content-Security-
 * Policy and everything alongside it come from the host. Generating the file
 * from the same module `next.config.ts` imports means the two cannot disagree,
 * and a reviewer only has one place to read the policy.
 *
 * Runs automatically before every build. The output is committed so the policy
 * is visible in review rather than materialising at deploy time.
 *
 * ⚠ Hosts that ignore `_headers` — GitHub Pages among them — serve the site
 * with no security headers at all. See DEPLOYMENT.md.
 *
 * Usage:  npm run headers:generate
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathHeaders, securityHeaders } from '../config/security-headers.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, 'public', '_headers');

/** Renders one `source` block in the `_headers` line format. */
function renderRule(source, headers) {
  const lines = headers.map(({ key, value }) => `  ${key}: ${value}`);
  return [source, ...lines].join('\n');
}

const banner = [
  '# Generated by scripts/generate-headers.mjs — do not edit by hand.',
  '# Source of truth: config/security-headers.mjs',
  '',
].join('\n');

// The catch-all comes first and the specific paths after it: both Cloudflare
// Pages and Netlify apply every matching rule in order, so a later, narrower
// block overrides the Cache-Control the wildcard would otherwise leave unset.
const body = [
  renderRule('/*', securityHeaders),
  ...pathHeaders.map(({ source, headers }) => renderRule(source, headers)),
].join('\n\n');

await writeFile(OUT, `${banner}${body}\n`, 'utf8');

console.log(`✔ Wrote ${pathHeaders.length + 1} header rules to public/_headers`);
