const CHAPTERS = [
  {
    id: 1,
    name: 'الفَاتِحة',
    nameSimple: 'الفاتحة',
    transliteration: 'Al-Fatihah',
    translation: 'The Opener',
    revelation: 'meccan',
    revelationOrder: 5,
    versesCount: 7,
    rukuCount: 1,
    startPage: 1,
    endPage: 1,
    startJuz: 1,
    endJuz: 1,
    hasBasmalah: false,
  },
  {
    id: 2,
    name: 'البَقَرَة',
    nameSimple: 'البقرة',
    transliteration: 'Al-Baqarah',
    translation: 'The Cow',
    revelation: 'medinan',
    revelationOrder: 87,
    versesCount: 286,
    rukuCount: 40,
    startPage: 2,
    endPage: 49,
    startJuz: 1,
    endJuz: 3,
    hasBasmalah: true,
  },
  {
    id: 3,
    name: 'آل عِمران',
    nameSimple: 'آل عمران',
    transliteration: "Ali 'Imran",
    translation: 'Family of Imran',
    revelation: 'medinan',
    revelationOrder: 89,
    versesCount: 200,
    rukuCount: 20,
    startPage: 50,
    endPage: 76,
    startJuz: 3,
    endJuz: 4,
    hasBasmalah: true,
  },
  {
    id: 4,
    name: 'النِّسَاء',
    nameSimple: 'النساء',
    transliteration: 'An-Nisa',
    translation: 'The Women',
    revelation: 'medinan',
    revelationOrder: 92,
    versesCount: 176,
    rukuCount: 24,
    startPage: 77,
    endPage: 106,
    startJuz: 4,
    endJuz: 6,
    hasBasmalah: true,
  },
  {
    id: 5,
    name: 'المَائدة',
    nameSimple: 'المائدة',
    transliteration: "Al-Ma'idah",
    translation: 'The Table Spread',
    revelation: 'medinan',
    revelationOrder: 112,
    versesCount: 120,
    rukuCount: 16,
    startPage: 106,
    endPage: 127,
    startJuz: 6,
    endJuz: 7,
    hasBasmalah: true,
  },
  {
    id: 6,
    name: 'الأنعَام',
    nameSimple: 'الأنعام',
    transliteration: "Al-An'am",
    translation: 'The Cattle',
    revelation: 'meccan',
    revelationOrder: 55,
    versesCount: 165,
    rukuCount: 20,
    startPage: 128,
    endPage: 150,
    startJuz: 7,
    endJuz: 8,
    hasBasmalah: true,
  },
  {
    id: 7,
    name: 'الأعرَاف',
    nameSimple: 'الأعراف',
    transliteration: "Al-A'raf",
    translation: 'The Heights',
    revelation: 'meccan',
    revelationOrder: 39,
    versesCount: 206,
    rukuCount: 24,
    startPage: 151,
    endPage: 176,
    startJuz: 8,
    endJuz: 9,
    hasBasmalah: true,
  },
  {
    id: 8,
    name: 'الأنفَال',
    nameSimple: 'الأنفال',
    transliteration: 'Al-Anfal',
    translation: 'The Spoils of War',
    revelation: 'medinan',
    revelationOrder: 88,
    versesCount: 75,
    rukuCount: 10,
    startPage: 177,
    endPage: 186,
    startJuz: 9,
    endJuz: 10,
    hasBasmalah: true,
  },
  {
    id: 9,
    name: 'التوبَة',
    nameSimple: 'التوبة',
    transliteration: 'At-Tawbah',
    translation: 'The Repentance',
    revelation: 'medinan',
    revelationOrder: 113,
    versesCount: 129,
    rukuCount: 16,
    startPage: 187,
    endPage: 207,
    startJuz: 10,
    endJuz: 11,
    hasBasmalah: false,
  },
  {
    id: 10,
    name: 'يُونس',
    nameSimple: 'يونس',
    transliteration: 'Yunus',
    translation: 'Jonah',
    revelation: 'meccan',
    revelationOrder: 51,
    versesCount: 109,
    rukuCount: 11,
    startPage: 208,
    endPage: 221,
    startJuz: 11,
    endJuz: 11,
    hasBasmalah: true,
  },
  {
    id: 11,
    name: 'هُود',
    nameSimple: 'هود',
    transliteration: 'Hud',
    translation: 'Hud',
    revelation: 'meccan',
    revelationOrder: 52,
    versesCount: 123,
    rukuCount: 10,
    startPage: 221,
    endPage: 235,
    startJuz: 11,
    endJuz: 12,
    hasBasmalah: true,
  },
  {
    id: 12,
    name: 'يُوسُف',
    nameSimple: 'يوسف',
    transliteration: 'Yusuf',
    translation: 'Joseph',
    revelation: 'meccan',
    revelationOrder: 53,
    versesCount: 111,
    rukuCount: 12,
    startPage: 235,
    endPage: 248,
    startJuz: 12,
    endJuz: 13,
    hasBasmalah: true,
  },
  {
    id: 13,
    name: 'الرَّعد',
    nameSimple: 'الرعد',
    transliteration: "Ar-Ra'd",
    translation: 'The Thunder',
    revelation: 'medinan',
    revelationOrder: 96,
    versesCount: 43,
    rukuCount: 6,
    startPage: 249,
    endPage: 255,
    startJuz: 13,
    endJuz: 13,
    hasBasmalah: true,
  },
  {
    id: 14,
    name: 'إبراهِيم',
    nameSimple: 'ابراهيم',
    transliteration: 'Ibrahim',
    translation: 'Abraham',
    revelation: 'meccan',
    revelationOrder: 72,
    versesCount: 52,
    rukuCount: 7,
    startPage: 255,
    endPage: 261,
    startJuz: 13,
    endJuz: 13,
    hasBasmalah: true,
  },
  {
    id: 15,
    name: 'الحِجر',
    nameSimple: 'الحجر',
    transliteration: 'Al-Hijr',
    translation: 'The Rocky Tract',
    revelation: 'meccan',
    revelationOrder: 54,
    versesCount: 99,
    rukuCount: 6,
    startPage: 262,
    endPage: 267,
    startJuz: 14,
    endJuz: 14,
    hasBasmalah: true,
  },
  {
    id: 16,
    name: 'النَّحل',
    nameSimple: 'النحل',
    transliteration: 'An-Nahl',
    translation: 'The Bee',
    revelation: 'meccan',
    revelationOrder: 70,
    versesCount: 128,
    rukuCount: 16,
    startPage: 267,
    endPage: 281,
    startJuz: 14,
    endJuz: 14,
    hasBasmalah: true,
  },
  {
    id: 17,
    name: 'الإسرَاء',
    nameSimple: 'الإسراء',
    transliteration: 'Al-Isra',
    translation: 'The Night Journey',
    revelation: 'meccan',
    revelationOrder: 50,
    versesCount: 111,
    rukuCount: 12,
    startPage: 282,
    endPage: 293,
    startJuz: 15,
    endJuz: 15,
    hasBasmalah: true,
  },
  {
    id: 18,
    name: 'الكَهف',
    nameSimple: 'الكهف',
    transliteration: 'Al-Kahf',
    translation: 'The Cave',
    revelation: 'meccan',
    revelationOrder: 69,
    versesCount: 110,
    rukuCount: 12,
    startPage: 293,
    endPage: 304,
    startJuz: 15,
    endJuz: 16,
    hasBasmalah: true,
  },
  {
    id: 19,
    name: 'مَريَم',
    nameSimple: 'مريم',
    transliteration: 'Maryam',
    translation: 'Mary',
    revelation: 'meccan',
    revelationOrder: 44,
    versesCount: 98,
    rukuCount: 6,
    startPage: 305,
    endPage: 312,
    startJuz: 16,
    endJuz: 16,
    hasBasmalah: true,
  },
  {
    id: 20,
    name: 'طه',
    nameSimple: 'طه',
    transliteration: 'Taha',
    translation: 'Ta-Ha',
    revelation: 'meccan',
    revelationOrder: 45,
    versesCount: 135,
    rukuCount: 8,
    startPage: 312,
    endPage: 321,
    startJuz: 16,
    endJuz: 16,
    hasBasmalah: true,
  },
  {
    id: 21,
    name: 'الأنبيَاء',
    nameSimple: 'الأنبياء',
    transliteration: 'Al-Anbya',
    translation: 'The Prophets',
    revelation: 'meccan',
    revelationOrder: 73,
    versesCount: 112,
    rukuCount: 7,
    startPage: 322,
    endPage: 331,
    startJuz: 17,
    endJuz: 17,
    hasBasmalah: true,
  },
  {
    id: 22,
    name: 'الحج',
    nameSimple: 'الحج',
    transliteration: 'Al-Hajj',
    translation: 'The Pilgrimage',
    revelation: 'medinan',
    revelationOrder: 103,
    versesCount: 78,
    rukuCount: 10,
    startPage: 332,
    endPage: 341,
    startJuz: 17,
    endJuz: 17,
    hasBasmalah: true,
  },
  {
    id: 23,
    name: 'المؤمنُون',
    nameSimple: 'المؤمنون',
    transliteration: "Al-Mu'minun",
    translation: 'The Believers',
    revelation: 'meccan',
    revelationOrder: 74,
    versesCount: 118,
    rukuCount: 6,
    startPage: 342,
    endPage: 349,
    startJuz: 18,
    endJuz: 18,
    hasBasmalah: true,
  },
  {
    id: 24,
    name: 'النور',
    nameSimple: 'النور',
    transliteration: 'An-Nur',
    translation: 'The Light',
    revelation: 'medinan',
    revelationOrder: 102,
    versesCount: 64,
    rukuCount: 9,
    startPage: 350,
    endPage: 359,
    startJuz: 18,
    endJuz: 18,
    hasBasmalah: true,
  },
  {
    id: 25,
    name: 'الفُرقَان',
    nameSimple: 'الفرقان',
    transliteration: 'Al-Furqan',
    translation: 'The Criterion',
    revelation: 'meccan',
    revelationOrder: 42,
    versesCount: 77,
    rukuCount: 6,
    startPage: 359,
    endPage: 366,
    startJuz: 18,
    endJuz: 19,
    hasBasmalah: true,
  },
  {
    id: 26,
    name: 'الشعراء',
    nameSimple: 'الشعراء',
    transliteration: "Ash-Shu'ara",
    translation: 'The Poets',
    revelation: 'meccan',
    revelationOrder: 47,
    versesCount: 227,
    rukuCount: 11,
    startPage: 367,
    endPage: 376,
    startJuz: 19,
    endJuz: 19,
    hasBasmalah: true,
  },
  {
    id: 27,
    name: 'النَّمل',
    nameSimple: 'النمل',
    transliteration: 'An-Naml',
    translation: 'The Ant',
    revelation: 'meccan',
    revelationOrder: 48,
    versesCount: 93,
    rukuCount: 7,
    startPage: 377,
    endPage: 385,
    startJuz: 19,
    endJuz: 20,
    hasBasmalah: true,
  },
  {
    id: 28,
    name: 'القَصَص',
    nameSimple: 'القصص',
    transliteration: 'Al-Qasas',
    translation: 'The Stories',
    revelation: 'meccan',
    revelationOrder: 49,
    versesCount: 88,
    rukuCount: 8,
    startPage: 385,
    endPage: 396,
    startJuz: 20,
    endJuz: 20,
    hasBasmalah: true,
  },
  {
    id: 29,
    name: 'العَنكبُوت',
    nameSimple: 'العنكبوت',
    transliteration: "Al-'Ankabut",
    translation: 'The Spider',
    revelation: 'meccan',
    revelationOrder: 85,
    versesCount: 69,
    rukuCount: 7,
    startPage: 396,
    endPage: 404,
    startJuz: 20,
    endJuz: 21,
    hasBasmalah: true,
  },
  {
    id: 30,
    name: 'الرُّوم',
    nameSimple: 'الروم',
    transliteration: 'Ar-Rum',
    translation: 'The Romans',
    revelation: 'meccan',
    revelationOrder: 84,
    versesCount: 60,
    rukuCount: 6,
    startPage: 404,
    endPage: 410,
    startJuz: 21,
    endJuz: 21,
    hasBasmalah: true,
  },
  {
    id: 31,
    name: 'لُقمَان',
    nameSimple: 'لقمان',
    transliteration: 'Luqman',
    translation: 'Luqman',
    revelation: 'meccan',
    revelationOrder: 57,
    versesCount: 34,
    rukuCount: 3,
    startPage: 411,
    endPage: 414,
    startJuz: 21,
    endJuz: 21,
    hasBasmalah: true,
  },
  {
    id: 32,
    name: 'السَّجدة',
    nameSimple: 'السجدة',
    transliteration: 'As-Sajdah',
    translation: 'The Prostration',
    revelation: 'meccan',
    revelationOrder: 75,
    versesCount: 30,
    rukuCount: 3,
    startPage: 415,
    endPage: 417,
    startJuz: 21,
    endJuz: 21,
    hasBasmalah: true,
  },
  {
    id: 33,
    name: 'الأحزَاب',
    nameSimple: 'الأحزاب',
    transliteration: 'Al-Ahzab',
    translation: 'The Combined Forces',
    revelation: 'medinan',
    revelationOrder: 90,
    versesCount: 73,
    rukuCount: 9,
    startPage: 418,
    endPage: 427,
    startJuz: 21,
    endJuz: 22,
    hasBasmalah: true,
  },
  {
    id: 34,
    name: 'سَبإ',
    nameSimple: 'سبإ',
    transliteration: 'Saba',
    translation: 'Sheba',
    revelation: 'meccan',
    revelationOrder: 58,
    versesCount: 54,
    rukuCount: 6,
    startPage: 428,
    endPage: 434,
    startJuz: 22,
    endJuz: 22,
    hasBasmalah: true,
  },
  {
    id: 35,
    name: 'فَاطِر',
    nameSimple: 'فاطر',
    transliteration: 'Fatir',
    translation: 'Originator',
    revelation: 'meccan',
    revelationOrder: 43,
    versesCount: 45,
    rukuCount: 5,
    startPage: 434,
    endPage: 440,
    startJuz: 22,
    endJuz: 22,
    hasBasmalah: true,
  },
  {
    id: 36,
    name: 'يسٓ',
    nameSimple: 'يس',
    transliteration: 'Ya-Sin',
    translation: 'Ya Sin',
    revelation: 'meccan',
    revelationOrder: 41,
    versesCount: 83,
    rukuCount: 5,
    startPage: 440,
    endPage: 445,
    startJuz: 22,
    endJuz: 23,
    hasBasmalah: true,
  },
  {
    id: 37,
    name: 'الصَّافَات',
    nameSimple: 'الصافات',
    transliteration: 'As-Saffat',
    translation: 'Those who set the Ranks',
    revelation: 'meccan',
    revelationOrder: 56,
    versesCount: 182,
    rukuCount: 5,
    startPage: 446,
    endPage: 452,
    startJuz: 23,
    endJuz: 23,
    hasBasmalah: true,
  },
  {
    id: 38,
    name: 'صٓ',
    nameSimple: 'ص',
    transliteration: 'Sad',
    translation: 'The Letter "Saad"',
    revelation: 'meccan',
    revelationOrder: 38,
    versesCount: 88,
    rukuCount: 5,
    startPage: 453,
    endPage: 458,
    startJuz: 23,
    endJuz: 23,
    hasBasmalah: true,
  },
  {
    id: 39,
    name: 'الزُّمَر',
    nameSimple: 'الزمر',
    transliteration: 'Az-Zumar',
    translation: 'The Troops',
    revelation: 'meccan',
    revelationOrder: 59,
    versesCount: 75,
    rukuCount: 8,
    startPage: 458,
    endPage: 467,
    startJuz: 23,
    endJuz: 24,
    hasBasmalah: true,
  },
  {
    id: 40,
    name: 'غَافِر',
    nameSimple: 'غافر',
    transliteration: 'Ghafir',
    translation: 'The Forgiver',
    revelation: 'meccan',
    revelationOrder: 60,
    versesCount: 85,
    rukuCount: 9,
    startPage: 467,
    endPage: 476,
    startJuz: 24,
    endJuz: 24,
    hasBasmalah: true,
  },
  {
    id: 41,
    name: 'فُصِّلَت',
    nameSimple: 'فصلت',
    transliteration: 'Fussilat',
    translation: 'Explained in Detail',
    revelation: 'meccan',
    revelationOrder: 61,
    versesCount: 54,
    rukuCount: 6,
    startPage: 477,
    endPage: 482,
    startJuz: 24,
    endJuz: 25,
    hasBasmalah: true,
  },
  {
    id: 42,
    name: 'الشُّوري',
    nameSimple: 'الشورى',
    transliteration: 'Ash-Shuraa',
    translation: 'The Consultation',
    revelation: 'meccan',
    revelationOrder: 62,
    versesCount: 53,
    rukuCount: 5,
    startPage: 483,
    endPage: 489,
    startJuz: 25,
    endJuz: 25,
    hasBasmalah: true,
  },
  {
    id: 43,
    name: 'الزُّخرُف',
    nameSimple: 'الزخرف',
    transliteration: 'Az-Zukhruf',
    translation: 'The Ornaments of Gold',
    revelation: 'meccan',
    revelationOrder: 63,
    versesCount: 89,
    rukuCount: 7,
    startPage: 489,
    endPage: 495,
    startJuz: 25,
    endJuz: 25,
    hasBasmalah: true,
  },
  {
    id: 44,
    name: 'الدُّخان',
    nameSimple: 'الدخان',
    transliteration: 'Ad-Dukhan',
    translation: 'The Smoke',
    revelation: 'meccan',
    revelationOrder: 64,
    versesCount: 59,
    rukuCount: 3,
    startPage: 496,
    endPage: 498,
    startJuz: 25,
    endJuz: 25,
    hasBasmalah: true,
  },
  {
    id: 45,
    name: 'الجاثِية',
    nameSimple: 'الجاثية',
    transliteration: 'Al-Jathiyah',
    translation: 'The Crouching',
    revelation: 'meccan',
    revelationOrder: 65,
    versesCount: 37,
    rukuCount: 4,
    startPage: 499,
    endPage: 502,
    startJuz: 25,
    endJuz: 25,
    hasBasmalah: true,
  },
  {
    id: 46,
    name: 'الأحقَاف',
    nameSimple: 'الأحقاف',
    transliteration: 'Al-Ahqaf',
    translation: 'The Wind-Curved Sandhills',
    revelation: 'meccan',
    revelationOrder: 66,
    versesCount: 35,
    rukuCount: 4,
    startPage: 502,
    endPage: 506,
    startJuz: 26,
    endJuz: 26,
    hasBasmalah: true,
  },
  {
    id: 47,
    name: 'مُحمد',
    nameSimple: 'محمد',
    transliteration: 'Muhammad',
    translation: 'Muhammad',
    revelation: 'medinan',
    revelationOrder: 95,
    versesCount: 38,
    rukuCount: 4,
    startPage: 507,
    endPage: 510,
    startJuz: 26,
    endJuz: 26,
    hasBasmalah: true,
  },
  {
    id: 48,
    name: 'الفَتح',
    nameSimple: 'الفتح',
    transliteration: 'Al-Fath',
    translation: 'The Victory',
    revelation: 'medinan',
    revelationOrder: 111,
    versesCount: 29,
    rukuCount: 4,
    startPage: 511,
    endPage: 515,
    startJuz: 26,
    endJuz: 26,
    hasBasmalah: true,
  },
  {
    id: 49,
    name: 'الحُجُرَات',
    nameSimple: 'الحجرات',
    transliteration: 'Al-Hujurat',
    translation: 'The Rooms',
    revelation: 'medinan',
    revelationOrder: 106,
    versesCount: 18,
    rukuCount: 2,
    startPage: 515,
    endPage: 517,
    startJuz: 26,
    endJuz: 26,
    hasBasmalah: true,
  },
  {
    id: 50,
    name: 'قٓ',
    nameSimple: 'ق',
    transliteration: 'Qaf',
    translation: 'The Letter "Qaf"',
    revelation: 'meccan',
    revelationOrder: 34,
    versesCount: 45,
    rukuCount: 3,
    startPage: 518,
    endPage: 520,
    startJuz: 26,
    endJuz: 26,
    hasBasmalah: true,
  },
  {
    id: 51,
    name: 'الذَّاريَات',
    nameSimple: 'الذاريات',
    transliteration: 'Adh-Dhariyat',
    translation: 'The Winnowing Winds',
    revelation: 'meccan',
    revelationOrder: 67,
    versesCount: 60,
    rukuCount: 3,
    startPage: 520,
    endPage: 523,
    startJuz: 26,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 52,
    name: 'الطُّور',
    nameSimple: 'الطور',
    transliteration: 'At-Tur',
    translation: 'The Mount',
    revelation: 'meccan',
    revelationOrder: 76,
    versesCount: 49,
    rukuCount: 2,
    startPage: 523,
    endPage: 525,
    startJuz: 27,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 53,
    name: 'النَّجم',
    nameSimple: 'النجم',
    transliteration: 'An-Najm',
    translation: 'The Star',
    revelation: 'meccan',
    revelationOrder: 23,
    versesCount: 62,
    rukuCount: 3,
    startPage: 526,
    endPage: 528,
    startJuz: 27,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 54,
    name: 'القَمَر',
    nameSimple: 'القمر',
    transliteration: 'Al-Qamar',
    translation: 'The Moon',
    revelation: 'meccan',
    revelationOrder: 37,
    versesCount: 55,
    rukuCount: 3,
    startPage: 528,
    endPage: 531,
    startJuz: 27,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 55,
    name: 'الرَّحمٰن',
    nameSimple: 'الرحمن',
    transliteration: 'Ar-Rahman',
    translation: 'The Beneficent',
    revelation: 'medinan',
    revelationOrder: 97,
    versesCount: 78,
    rukuCount: 3,
    startPage: 531,
    endPage: 534,
    startJuz: 27,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 56,
    name: 'الوَاقِعة',
    nameSimple: 'الواقعة',
    transliteration: "Al-Waqi'ah",
    translation: 'The Inevitable',
    revelation: 'meccan',
    revelationOrder: 46,
    versesCount: 96,
    rukuCount: 3,
    startPage: 534,
    endPage: 537,
    startJuz: 27,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 57,
    name: 'الحدِيد',
    nameSimple: 'الحديد',
    transliteration: 'Al-Hadid',
    translation: 'The Iron',
    revelation: 'medinan',
    revelationOrder: 94,
    versesCount: 29,
    rukuCount: 4,
    startPage: 537,
    endPage: 541,
    startJuz: 27,
    endJuz: 27,
    hasBasmalah: true,
  },
  {
    id: 58,
    name: 'المُجَادلة',
    nameSimple: 'المجادلة',
    transliteration: 'Al-Mujadila',
    translation: 'The Pleading Woman',
    revelation: 'medinan',
    revelationOrder: 105,
    versesCount: 22,
    rukuCount: 3,
    startPage: 542,
    endPage: 545,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 59,
    name: 'الحَشر',
    nameSimple: 'الحشر',
    transliteration: 'Al-Hashr',
    translation: 'The Exile',
    revelation: 'medinan',
    revelationOrder: 101,
    versesCount: 24,
    rukuCount: 3,
    startPage: 545,
    endPage: 548,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 60,
    name: 'المُمتَحنَة',
    nameSimple: 'الممتحنة',
    transliteration: 'Al-Mumtahanah',
    translation: 'She that is to be examined',
    revelation: 'medinan',
    revelationOrder: 91,
    versesCount: 13,
    rukuCount: 2,
    startPage: 549,
    endPage: 551,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 61,
    name: 'الصَّف',
    nameSimple: 'الصف',
    transliteration: 'As-Saf',
    translation: 'The Ranks',
    revelation: 'medinan',
    revelationOrder: 109,
    versesCount: 14,
    rukuCount: 2,
    startPage: 551,
    endPage: 552,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 62,
    name: 'الجُمعَة',
    nameSimple: 'الجمعة',
    transliteration: "Al-Jumu'ah",
    translation: 'The Congregation, Friday',
    revelation: 'medinan',
    revelationOrder: 110,
    versesCount: 11,
    rukuCount: 2,
    startPage: 553,
    endPage: 554,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 63,
    name: 'المُنَافِقُونَ',
    nameSimple: 'المنافقون',
    transliteration: 'Al-Munafiqun',
    translation: 'The Hypocrites',
    revelation: 'medinan',
    revelationOrder: 104,
    versesCount: 11,
    rukuCount: 2,
    startPage: 554,
    endPage: 555,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 64,
    name: 'التغَابُن',
    nameSimple: 'التغابن',
    transliteration: 'At-Taghabun',
    translation: 'The Mutual Disillusion',
    revelation: 'medinan',
    revelationOrder: 108,
    versesCount: 18,
    rukuCount: 2,
    startPage: 556,
    endPage: 557,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 65,
    name: 'الطَّلَاق',
    nameSimple: 'الطلاق',
    transliteration: 'At-Talaq',
    translation: 'The Divorce',
    revelation: 'medinan',
    revelationOrder: 99,
    versesCount: 12,
    rukuCount: 2,
    startPage: 558,
    endPage: 559,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 66,
    name: 'التَّحرِيم',
    nameSimple: 'التحريم',
    transliteration: 'At-Tahrim',
    translation: 'The Prohibition',
    revelation: 'medinan',
    revelationOrder: 107,
    versesCount: 12,
    rukuCount: 2,
    startPage: 560,
    endPage: 561,
    startJuz: 28,
    endJuz: 28,
    hasBasmalah: true,
  },
  {
    id: 67,
    name: 'المُلك',
    nameSimple: 'الملك',
    transliteration: 'Al-Mulk',
    translation: 'The Sovereignty',
    revelation: 'meccan',
    revelationOrder: 77,
    versesCount: 30,
    rukuCount: 2,
    startPage: 562,
    endPage: 564,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 68,
    name: 'القَلَم',
    nameSimple: 'القلم',
    transliteration: 'Al-Qalam',
    translation: 'The Pen',
    revelation: 'meccan',
    revelationOrder: 2,
    versesCount: 52,
    rukuCount: 2,
    startPage: 564,
    endPage: 566,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 69,
    name: 'الحَاقة',
    nameSimple: 'الحاقة',
    transliteration: 'Al-Haqqah',
    translation: 'The Reality',
    revelation: 'meccan',
    revelationOrder: 78,
    versesCount: 52,
    rukuCount: 2,
    startPage: 566,
    endPage: 568,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 70,
    name: 'المَعَارج',
    nameSimple: 'المعارج',
    transliteration: "Al-Ma'arij",
    translation: 'The Ascending Stairways',
    revelation: 'meccan',
    revelationOrder: 79,
    versesCount: 44,
    rukuCount: 2,
    startPage: 568,
    endPage: 570,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 71,
    name: 'نُوح',
    nameSimple: 'نوح',
    transliteration: 'Nuh',
    translation: 'Noah',
    revelation: 'meccan',
    revelationOrder: 71,
    versesCount: 28,
    rukuCount: 2,
    startPage: 570,
    endPage: 571,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 72,
    name: 'الجِن',
    nameSimple: 'الجن',
    transliteration: 'Al-Jinn',
    translation: 'The Jinn',
    revelation: 'meccan',
    revelationOrder: 40,
    versesCount: 28,
    rukuCount: 2,
    startPage: 572,
    endPage: 573,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 73,
    name: 'المُزمل',
    nameSimple: 'المزمل',
    transliteration: 'Al-Muzzammil',
    translation: 'The Enshrouded One',
    revelation: 'meccan',
    revelationOrder: 3,
    versesCount: 20,
    rukuCount: 2,
    startPage: 574,
    endPage: 575,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 74,
    name: 'المُدثر',
    nameSimple: 'المدثر',
    transliteration: 'Al-Muddaththir',
    translation: 'The Cloaked One',
    revelation: 'meccan',
    revelationOrder: 4,
    versesCount: 56,
    rukuCount: 2,
    startPage: 575,
    endPage: 577,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 75,
    name: 'القِيَامة',
    nameSimple: 'القيامة',
    transliteration: 'Al-Qiyamah',
    translation: 'The Resurrection',
    revelation: 'meccan',
    revelationOrder: 31,
    versesCount: 40,
    rukuCount: 2,
    startPage: 577,
    endPage: 578,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 76,
    name: 'الإنسَان',
    nameSimple: 'الانسان',
    transliteration: 'Al-Insan',
    translation: 'The Man',
    revelation: 'medinan',
    revelationOrder: 98,
    versesCount: 31,
    rukuCount: 2,
    startPage: 578,
    endPage: 580,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 77,
    name: 'المُرسَلات',
    nameSimple: 'المرسلات',
    transliteration: 'Al-Mursalat',
    translation: 'The Emissaries',
    revelation: 'meccan',
    revelationOrder: 33,
    versesCount: 50,
    rukuCount: 2,
    startPage: 580,
    endPage: 581,
    startJuz: 29,
    endJuz: 29,
    hasBasmalah: true,
  },
  {
    id: 78,
    name: 'النَّبَإ',
    nameSimple: 'النبإ',
    transliteration: 'An-Naba',
    translation: 'The Tidings',
    revelation: 'meccan',
    revelationOrder: 80,
    versesCount: 40,
    rukuCount: 2,
    startPage: 582,
    endPage: 583,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 79,
    name: 'النَّازعَات',
    nameSimple: 'النازعات',
    transliteration: "An-Nazi'at",
    translation: 'Those who drag forth',
    revelation: 'meccan',
    revelationOrder: 81,
    versesCount: 46,
    rukuCount: 2,
    startPage: 583,
    endPage: 584,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 80,
    name: 'عَبَسَ',
    nameSimple: 'عبس',
    transliteration: "'Abasa",
    translation: 'He Frowned',
    revelation: 'meccan',
    revelationOrder: 24,
    versesCount: 42,
    rukuCount: 1,
    startPage: 585,
    endPage: 585,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 81,
    name: 'التَّكوير',
    nameSimple: 'التكوير',
    transliteration: 'At-Takwir',
    translation: 'The Overthrowing',
    revelation: 'meccan',
    revelationOrder: 7,
    versesCount: 29,
    rukuCount: 1,
    startPage: 586,
    endPage: 586,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 82,
    name: 'الانفِطَار',
    nameSimple: 'الإنفطار',
    transliteration: 'Al-Infitar',
    translation: 'The Cleaving',
    revelation: 'meccan',
    revelationOrder: 82,
    versesCount: 19,
    rukuCount: 1,
    startPage: 587,
    endPage: 587,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 83,
    name: 'المُطَففين',
    nameSimple: 'المطففين',
    transliteration: 'Al-Mutaffifin',
    translation: 'The Defrauding',
    revelation: 'meccan',
    revelationOrder: 86,
    versesCount: 36,
    rukuCount: 1,
    startPage: 587,
    endPage: 589,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 84,
    name: 'الانشِقَاق',
    nameSimple: 'الإنشقاق',
    transliteration: 'Al-Inshiqaq',
    translation: 'The Sundering',
    revelation: 'meccan',
    revelationOrder: 83,
    versesCount: 25,
    rukuCount: 1,
    startPage: 589,
    endPage: 589,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 85,
    name: 'البُرُوج',
    nameSimple: 'البروج',
    transliteration: 'Al-Buruj',
    translation: 'The Mansions of the Stars',
    revelation: 'meccan',
    revelationOrder: 27,
    versesCount: 22,
    rukuCount: 1,
    startPage: 590,
    endPage: 590,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 86,
    name: 'الطَّارق',
    nameSimple: 'الطارق',
    transliteration: 'At-Tariq',
    translation: 'The Nightcommer',
    revelation: 'meccan',
    revelationOrder: 36,
    versesCount: 17,
    rukuCount: 1,
    startPage: 591,
    endPage: 591,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 87,
    name: 'الأعلى',
    nameSimple: 'الأعلى',
    transliteration: "Al-A'la",
    translation: 'The Most High',
    revelation: 'meccan',
    revelationOrder: 8,
    versesCount: 19,
    rukuCount: 1,
    startPage: 591,
    endPage: 592,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 88,
    name: 'الغَاشِية',
    nameSimple: 'الغاشية',
    transliteration: 'Al-Ghashiyah',
    translation: 'The Overwhelming',
    revelation: 'meccan',
    revelationOrder: 68,
    versesCount: 26,
    rukuCount: 1,
    startPage: 592,
    endPage: 592,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 89,
    name: 'الفَجر',
    nameSimple: 'الفجر',
    transliteration: 'Al-Fajr',
    translation: 'The Dawn',
    revelation: 'meccan',
    revelationOrder: 10,
    versesCount: 30,
    rukuCount: 1,
    startPage: 593,
    endPage: 594,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 90,
    name: 'البَلَد',
    nameSimple: 'البلد',
    transliteration: 'Al-Balad',
    translation: 'The City',
    revelation: 'meccan',
    revelationOrder: 35,
    versesCount: 20,
    rukuCount: 1,
    startPage: 594,
    endPage: 594,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 91,
    name: 'الشَّمس',
    nameSimple: 'الشمس',
    transliteration: 'Ash-Shams',
    translation: 'The Sun',
    revelation: 'meccan',
    revelationOrder: 26,
    versesCount: 15,
    rukuCount: 1,
    startPage: 595,
    endPage: 595,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 92,
    name: 'اللَّيل',
    nameSimple: 'الليل',
    transliteration: 'Al-Layl',
    translation: 'The Night',
    revelation: 'meccan',
    revelationOrder: 9,
    versesCount: 21,
    rukuCount: 1,
    startPage: 595,
    endPage: 596,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 93,
    name: 'الضُّحى',
    nameSimple: 'الضحى',
    transliteration: 'Ad-Duhaa',
    translation: 'The Morning Hours',
    revelation: 'meccan',
    revelationOrder: 11,
    versesCount: 11,
    rukuCount: 1,
    startPage: 596,
    endPage: 596,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 94,
    name: 'الشَّرح',
    nameSimple: 'الشرح',
    transliteration: 'Ash-Sharh',
    translation: 'The Relief',
    revelation: 'meccan',
    revelationOrder: 12,
    versesCount: 8,
    rukuCount: 1,
    startPage: 596,
    endPage: 596,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 95,
    name: 'التِّين',
    nameSimple: 'التين',
    transliteration: 'At-Tin',
    translation: 'The Fig',
    revelation: 'meccan',
    revelationOrder: 28,
    versesCount: 8,
    rukuCount: 1,
    startPage: 597,
    endPage: 597,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 96,
    name: 'العَلَق',
    nameSimple: 'العلق',
    transliteration: "Al-'Alaq",
    translation: 'The Clot',
    revelation: 'meccan',
    revelationOrder: 1,
    versesCount: 19,
    rukuCount: 1,
    startPage: 597,
    endPage: 597,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 97,
    name: 'القَدر',
    nameSimple: 'القدر',
    transliteration: 'Al-Qadr',
    translation: 'The Power',
    revelation: 'meccan',
    revelationOrder: 25,
    versesCount: 5,
    rukuCount: 1,
    startPage: 598,
    endPage: 598,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 98,
    name: 'البَينَة',
    nameSimple: 'البينة',
    transliteration: 'Al-Bayyinah',
    translation: 'The Clear Proof',
    revelation: 'medinan',
    revelationOrder: 100,
    versesCount: 8,
    rukuCount: 1,
    startPage: 598,
    endPage: 599,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 99,
    name: 'الزَّلزَلة',
    nameSimple: 'الزلزلة',
    transliteration: 'Az-Zalzalah',
    translation: 'The Earthquake',
    revelation: 'medinan',
    revelationOrder: 93,
    versesCount: 8,
    rukuCount: 1,
    startPage: 599,
    endPage: 599,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 100,
    name: 'العَاديَات',
    nameSimple: 'العاديات',
    transliteration: "Al-'Adiyat",
    translation: 'The Courser',
    revelation: 'meccan',
    revelationOrder: 14,
    versesCount: 11,
    rukuCount: 1,
    startPage: 599,
    endPage: 600,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 101,
    name: 'القَارعَة',
    nameSimple: 'القارعة',
    transliteration: "Al-Qari'ah",
    translation: 'The Calamity',
    revelation: 'meccan',
    revelationOrder: 30,
    versesCount: 11,
    rukuCount: 1,
    startPage: 600,
    endPage: 600,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 102,
    name: 'التَّكاثُر',
    nameSimple: 'التكاثر',
    transliteration: 'At-Takathur',
    translation: 'The Rivalry in world increase',
    revelation: 'meccan',
    revelationOrder: 16,
    versesCount: 8,
    rukuCount: 1,
    startPage: 600,
    endPage: 600,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 103,
    name: 'العَصر',
    nameSimple: 'العصر',
    transliteration: "Al-'Asr",
    translation: 'The Declining Day',
    revelation: 'meccan',
    revelationOrder: 13,
    versesCount: 3,
    rukuCount: 1,
    startPage: 601,
    endPage: 601,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 104,
    name: 'الهُمَزة',
    nameSimple: 'الهمزة',
    transliteration: 'Al-Humazah',
    translation: 'The Traducer',
    revelation: 'meccan',
    revelationOrder: 32,
    versesCount: 9,
    rukuCount: 1,
    startPage: 601,
    endPage: 601,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 105,
    name: 'الفِيل',
    nameSimple: 'الفيل',
    transliteration: 'Al-Fil',
    translation: 'The Elephant',
    revelation: 'meccan',
    revelationOrder: 19,
    versesCount: 5,
    rukuCount: 1,
    startPage: 601,
    endPage: 601,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 106,
    name: 'قُرَيش',
    nameSimple: 'قريش',
    transliteration: 'Quraysh',
    translation: 'Quraysh',
    revelation: 'meccan',
    revelationOrder: 29,
    versesCount: 4,
    rukuCount: 1,
    startPage: 602,
    endPage: 602,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 107,
    name: 'المَاعُون',
    nameSimple: 'الماعون',
    transliteration: "Al-Ma'un",
    translation: 'The Small kindnesses',
    revelation: 'meccan',
    revelationOrder: 17,
    versesCount: 7,
    rukuCount: 1,
    startPage: 602,
    endPage: 602,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 108,
    name: 'الكَوثر',
    nameSimple: 'الكوثر',
    transliteration: 'Al-Kawthar',
    translation: 'The Abundance',
    revelation: 'meccan',
    revelationOrder: 15,
    versesCount: 3,
    rukuCount: 1,
    startPage: 602,
    endPage: 602,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 109,
    name: 'الكافِرون',
    nameSimple: 'الكافرون',
    transliteration: 'Al-Kafirun',
    translation: 'The Disbelievers',
    revelation: 'meccan',
    revelationOrder: 18,
    versesCount: 6,
    rukuCount: 1,
    startPage: 603,
    endPage: 603,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 110,
    name: 'النَّصر',
    nameSimple: 'النصر',
    transliteration: 'An-Nasr',
    translation: 'The Divine Support',
    revelation: 'medinan',
    revelationOrder: 114,
    versesCount: 3,
    rukuCount: 1,
    startPage: 603,
    endPage: 603,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 111,
    name: 'المَسَد',
    nameSimple: 'المسد',
    transliteration: 'Al-Masad',
    translation: 'The Palm Fiber',
    revelation: 'meccan',
    revelationOrder: 6,
    versesCount: 5,
    rukuCount: 1,
    startPage: 603,
    endPage: 603,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 112,
    name: 'الإخلَاص',
    nameSimple: 'الإخلاص',
    transliteration: 'Al-Ikhlas',
    translation: 'The Sincerity',
    revelation: 'meccan',
    revelationOrder: 22,
    versesCount: 4,
    rukuCount: 1,
    startPage: 604,
    endPage: 604,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 113,
    name: 'الفَلَق',
    nameSimple: 'الفلق',
    transliteration: 'Al-Falaq',
    translation: 'The Daybreak',
    revelation: 'meccan',
    revelationOrder: 20,
    versesCount: 5,
    rukuCount: 1,
    startPage: 604,
    endPage: 604,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
  {
    id: 114,
    name: 'النَّاس',
    nameSimple: 'الناس',
    transliteration: 'An-Nas',
    translation: 'Mankind',
    revelation: 'meccan',
    revelationOrder: 21,
    versesCount: 6,
    rukuCount: 1,
    startPage: 604,
    endPage: 604,
    startJuz: 30,
    endJuz: 30,
    hasBasmalah: true,
  },
];
